facuparedes/EventIn

- src/screens/FormEvent/FormEvent.jsx
1) Importo la clase Event a EventForm.jsx
2) Cambio la función handleSubmit, utilizando Event.create() (previamente pasando fee a Number)
3) Valido que el campo photo exista (falta validar que sea url)
> change to handleSubmit

- src/screens/FormEvent/FormEvent.jsx
Fixed redirect to Home after creating an event.
> fix redirect post create event

- package.json
- src/common/components/CardsFlat/CardsFlat.jsx
- src/common/redux/actions.js
- src/common/redux/reducer.js
- src/screens/Home/Home.jsx
- src/screens/Home/styles.js
En Home puse un picker para el filtro por categoria, tuve que modificar varios archivos, porque ahora los dispatch al Estado se hacen desde el home. Funciona ok. 
Pruébenlo please.(y aprueben!!!!)
> Filter by Category created

- App.js
- package.json
- src/routes/TabBar.jsx
- src/screens/Edit Profile/EditProfile.jsx
- src/screens/Edit Profile/styles.js
- src/screens/Profile/Profile.jsx
- src/screens/Profile/styles.js
Crear el screen de profile y de edit profile
> Profile screen

- package.json
Ahí eliminé la coma que hace que se crashee todo! Solo hice eso, asi que cuando puedan, aprueben y mergeo
> fixed error in package.json

- src/screens/Home/Home.jsx
Tuve que agregar al picker de categorias, una cat Todas, fue la unica manera, ya que despues de hacer un Search x nombre, no se volvian a renderizar todos los eventos, porque el picker trabaja solo cuando hay un onChangeValue,
> fix-bug-with-SearchName

- src/routes/TabBar.jsx
- src/screens/Home/Home.jsx
Arreglo de la opción cancelar en el alert de Cerrar sesión de la screen Perfil.
> fixed cancel bug in Profile

- src/common/components/Search/styles.js
- src/common/redux/actions.js
condicional en la getEvenstbyName y tamaño del input y el fontsize
> condicional en getEventsByName y tamaño del input

- src/common/components/Card/Card.jsx
- src/common/components/DatePicker/DatePicker.jsx
- src/common/redux/actions.js
- src/common/redux/reducer.js
- src/screens/Home/Home.jsx
incluí un icono al lado de Categoria, abre un calendario, para seleccionar la fecha de la busqueda, el problema es que el find no me trae el/los eventos de ese dia, x el find de firebase, porque aunq sea el mismo dia, el time es distinto. 
Tb agregué un alert en el filtro de categoría x si no hay ventos en esa categoria.
Para lo del Date, hice un nuevo componente(DatePicker) que se renderiza en el Home, , y una nueva action de redux. , que se despacha en la funcion  onChange del nuevo componente.
> findByDate in process

- src/common/components/DatePicker/DatePicker.jsx
- src/screens/Home/Home.jsx
- src/screens/Home/styles.js
> fix home filters

- src/common/components/DatePicker/DatePicker.jsx
- src/common/redux/actions.js
-búsqueda de eventos por fecha desde el calendario funcionando
> fix-findByDate

- src/common/components/Card/styles.js
- src/screens/Card Detail/CardDetail.jsx
- src/screens/Card Detail/CardDetailStyles.js
Modifiqué el estilo del detail! 
Agregué una flatList en el final para mostrar el resto de imágenes que suba el usuario, pero me di cuenta que siempre se sube la misma imagen! Nosé como solucionar eso!
también solucioné problemas de responsive!
> fixed cardDetail

- api/firebase/models/event.js
> productionFix

- src/screens/Card Detail/CardDetail.jsx
- src/screens/Card Detail/CardDetailStyles.js
Disminuí el tamaño de la letra del precio para resolver el problema de la visual en dispositivos angostos!
Le puse color al título, precio y dirección.
Por último configuré que si el precio es 0, renderice Gratis.
> minimize font fee & add color in fonts

- package.json
- src/common/redux/actions.js
- src/common/redux/reducer.js
Al traer todos los eventos, los muestra ordenados por fecha , y no se muestran los que ya finalizaron.
Al buscar x categoria tampoco se muestran los finalizados.
Tuve que usar en el reduce un sort, y un filter porque firebase no me permite hacer búsquedas compuestas.
> events sorted by date- not show fineshed events

- src/screens/Home/Home.jsx
Arreglé que queden fijon los botenes de Categoria y buscar por fecha, al hacer scroll en el Home, y cambie paar que el refresh funcione bien sin tener ese problema del scroll
> fix-refresh-Static filter buttons

- App.js
- src/screens/Card Detail/CardDetail.jsx
- src/screens/Card Detail/MapDetail.jsx
ahora la foto del mapa que esta en el datail es un boton , y te lleva a una screen que esta el mapa con un pin fijo. El pin esta en la ubicación elegida del evento , también cuando apretas el pin te muestra el nombre del evento.
> Icono del mapa renderiza el mapa

- src/common/components/Card/Card.jsx
- src/common/components/CardsFlat/CardsFlat.jsx
En los eventos que ya empezaron, se lee "en curso" en lugar del tiempo que hace que empezó (ej: "hace 4 horas"). En los eventos que aún no empiezan queda como estaba ej: "en 2 dias"
> event in progress when it already started

- src/screens/Card Detail/CardDetail.jsx
Agregué la fecha de finalización del evento.
Corregí un pequeño detalle cuando tocaba el mapa (se veía algo feo detrás del mapa)
> add date end in cardDetail

- api/firebase/models/event.js
Reastree el error del renderizado de la galeria de fotos en CardDetail, habia un bug en el modelo Event, con el asesoramiento de Facu, se arregló.
> fix-model Event for render photos in CardDetail

- src/routes/TabBar.jsx
- src/routes/styles.js
- src/screens/Profile/styles.js
Arregle algunos bugs del drawer de editar perfil y editar contraseña. Y cambie un poco el estilo del perfil para que sea responsive
> Styles profile

- src/screens/Card Detail/CardDetail.jsx
- src/screens/FormEvent/CardPreviewStyles.js
- src/screens/FormEvent/FormCardPreview.jsx
- src/screens/FormEvent/FormMaps.jsx
- src/screens/Register/Register.jsx
Saqué la dirección del detail y el preview del form.
También comenté el search input del map y el botón del register con Google.
> Edit detail and form preview

- src/common/redux/reducer.js
- src/screens/FormEvent/FormEvent.jsx
- src/screens/FormEvent/Title_Fee_Desc.jsx
- En el Profile, ahora los eventos favoritos se ordenan por fecha mas próxima a mas lejanos, en el reducer hice el ordenamiento con un sort.
- Comenté en el código el boton de videos para que no se puedan agregar en el Formulario, y cambie algunos títulos para que no estuviera la palabra "video/s"
> Profile- eventes likes on date order & commented videos button in Form

- package.json
- src/screens/WebViewScreen/WebViewScreen.jsx
> justOneLoading

- src/common/components/Card/Card.jsx
- src/common/components/Card/styles.js
- src/routes/TabBar.jsx
- src/routes/styles.js
- src/screens/Edit Profile/EditProfile.jsx
- src/screens/Profile/Profile.jsx
- src/screens/Profile/styles.js
Eliminé el botón de compartir de las cards.
Apliqué un poco de CSS en el Profile donde Andy agregó la sección de eventos creados.
También edité las fuentes del menú del Profile.
> delete btn share & edit styles Profile

- src/screens/Card Detail/CardDetail.jsx
No se choreen la Key de Andy ;)
> anotherKey

- src/common/components/DatePicker/DatePicker.jsx
- src/common/redux/actions.js
- src/common/redux/reducer.js
-Apliqué un filter extra para que se rendericen solo los eventos con publicación pagada activa
- Funciona en el home, y tambien en cada filtro (categoria y fecha)
- Ahora el filtro por fecha, no trae solo los q empiezan en esa fecha, sino tb los eventos que aun no han finalizado  estan en curso
- IMPORTANTE: si crean eventos con publicacion a partir de otra fecha que no sea hoy, no se les van a renderizar hasta que sea esa fecha
> Publication date

- src/screens/Card Detail/CardDetail.jsx
- src/screens/Home/Home.jsx
Arreglo el bug del navegador como invitado, pero se genera otro con el renderizado del likes al iniciar sesión (que es menor al primero)
> solved loggedOut, like problems logged now

- src/common/components/Card/Card.jsx
- src/common/components/CardsFlatCreatedEvents/CardsFlatCreatedEvents.jsx
- src/common/redux/actions.js
- src/common/redux/reducer.js
- src/screens/Card Detail/CardDetail.jsx
- src/screens/Profile/Profile.jsx
Arreglo del detail cuando se navega desde el perfil/eventos creados
> fixed bug detail created event

- src/common/components/Card/Card.jsx
- src/common/components/Card/styles.js
- src/common/components/Search/Search.jsx
- src/common/components/Search/styles.js
- src/screens/Card Detail/CardDetail.jsx
- src/screens/Card Detail/CardDetailStyles.js
- src/screens/Home/Home.jsx
- src/screens/Home/styles.js
Quité el botón de compartir en el CardDetail y modifiqué solo la fuente del Search
> delete btn share in Detail & change fonts search

- App.js
- api/firebase/config.js
Esto elimina todos  los warnings de toda la app. Dejo el PR por si nos es útil mas tarde incorporarlo.
> Hidden warnings

- src/common/redux/reducer.js
- src/screens/FormEvent/FormCardPreview.jsx
- src/screens/FormEvent/Title_Fee_Desc.jsx
Soluciona un Bug cuando cerras sesión y vas a crear un evento
> fixSingOut
